Add pg_cron, install to postgres database in image build
CircleCI-Public/cimg-postgres pull request #72
Opened 2023-02-27 22:27 UTC by cci-jsmith

- clones and installs pg_cron.
- writes a custom conf file which installs pg_cron and makes it available for `create extension pg_cron;`

2023-02-28 12:00 UTC, BytesGuy requested changes
This seems ok to me, but I will also ask for a review from @felicianotech as I am not overly familiar with Postgres extensions!

2023-02-28 12:00 UTC, BytesGuy commented on Dockerfile.template
> +
This blank line can be removed

2023-03-09 10:35 UTC, BytesGuy commented
@cci-jsmith We will loop round to this after the work in #74 and #67 is done 👍

2023-03-29 08:27 UTC, BytesGuy commented
@JalexChen Can you look at this PR after the previous blocking PRs have been merged?

2023-03-29 19:13 UTC, JalexChen requested changes

2023-03-29 19:13 UTC, JalexChen commented on Dockerfile.template
> +	echo "shared_preload_libraries = 'pg_cron'" >> $cron_conf && \
now that the `postgres.conf` file has been merged in, do you want to move some of these changes over to that file or make a separate one for the custom-cron.conf? something like:
```
shared_preload_libraries = 'pg_cron'
cron.database_name = 'postgres'
```
and 
`include = '/var/lib/postgresql/data/custom-conf.conf'` in `postgres.conf`

2023-03-29 19:23 UTC, JalexChen commented on Dockerfile.template
> +	cd pg_cron && make && make install && \
additionally, can we also make sure the PATH is correct for users to use it? 

from their docs, the `pgsql-15` would need to work for postgres10+, so something like `pgsql-"$PG_MAJOR"`. i would need to check if that nomenclature has changed
```
git clone https://github.com/citusdata/pg_cron.git
cd pg_cron
# Ensure pg_config is in your path, e.g.
export PATH=/usr/pgsql-15/bin:$PATH
make && sudo PATH=$PATH make install
```

2023-05-08 22:56 UTC, JalexChen commented
Closing in favor of #83

2023-05-08 22:56 UTC, closed without merging

2025-07-16 13:41 UTC, donnykurnia commented
Why is this feature needed? Why it is not in the documentation? And please look at https://github.com/CircleCI-Public/cimg-postgres/issues/116 and add an option to disable this feature.